### ISSUE TITLE
Add helper method to get Organization by nameKey

### ISSUE THREAD

**Issue by dalelotts** [stormpath/stormpath-sdk-dotnet#137]
When working in a multi-tenant application it would be ideal to get an Organization by name.

Currently I must query the list of organizations to find the one with the specified name.

**Comment by nbarbettini** [comment]
Just to clarify: Since we've already got an `IClient.GetOrganizationAsync(href)` method, you're proposing adding additional logic so it can detect if an Organization nameKey is passed instead of an href. Correct?

Internally, it would simply run something like

```
client.GetOrganizations().Where(org => org.Name == nameKey).SingleOrDefault()
```

and return.

**Comment by dalelotts** [comment]
Yes, you are correct. Thanks

**Comment by dalelotts** [comment]
Looking at the code, should this also be changed for ITenant implementations?

**Comment by nbarbettini** [comment]
This method actually lives in [ITenantActions](http://docs.stormpath.com/dotnet/api/html/T_Stormpath_SDK_Tenant_ITenantActions.htm), which is implemented by both `ITenant` and `IClient`. So, it should only need to be added to that interface. :+1:

**Comment by dalelotts** [comment]
So, just to be clear, as we are working on a PR:

Add another method to  ITenantActions? i.e. GetOrganizationByNameAsync(name)  
OR
change signature of GetOrganizationAsync to GetOrganizationAsync(hrefOrName) and update the implementation to detect href vs name.

**Comment by nbarbettini** [comment]
I'd prefer a separate method because it's more descriptive and less confusing. :+1: There are some other methods in the SDK that use the `string hrefOrNameKey` signature but I'd like to move away from that.

Thanks (in advance) for the contribution! Since I don't have proper instructions in CONTRIBUTING.md yet, here are some things off the top of my head:
- Add the new method to the interface (`ITenantActions`)
- Implement in the proper classes. In this case, `DefaultClient.TenantActions` and `DefaultTenant.TenantActions`. Note that the implementation is only in one place - should be clear by looking at the classes.
- Add a synchronous extension method (`SyncTenantActionsExtensions`)
- Add the sync method to the sync interface (`ITenantActionsSync`)
- Implement in the proper classes (`DefaultClient.TenantActionsSync`, `DefaultTenant.TenantActionsSync`)
- Make sure Stormpath.SDK.Tests and Stormpath.SDK.Tests.Sanity pass
- Don't worry about writing any tests for now, I'll take care of that
- Open a PR against `develop`

Hopefully that's not too confusing! Let me know if you have any questions.

**Comment by jwynia** [comment]
Nate, I'm the one who ended up attempting to implement this change on the team Dale's on to get you the PR.

I went through the path of interfaces and extensions, implementing `GetOrganizationByName(string nameKey, CancellationToken cancellationToken)` and matching `GetOrganization` along the way.

I'm in the `DefaultTenant.TenantActions` and `DefaultTenant.TenantActionsSync` looking to do the implementation and am wondering if what it looks like I have to do is correct or is just my misunderstanding things. From what I can see, to get the organizations to query, I have to do a bit of casting and something like this in the async version:

`return ((ITenantActions) this).GetOrganizations().Where(org => org.Name == nameKey).SingleOrDefaultAsync();`

and a slightly more convoluted path for the sync implementation since I don't see a non async way to GetOrganizations

`return ((ITenantActions)this).GetOrganizations().Where(org => org.Name == nameKey).SingleOrDefaultAsync().Result;`

Is there a better way to get the overall list of organizations to query in those 2 spots or is this the right way? Or am I completely off in the weeds on this?

**Comment by nbarbettini** [comment]
Hi @jwynia, thanks for working on this!

You can use the private field `AsInterface` to make this a little easier:

```
return this.AsInterface.GetOrganizations()
    .Where(org => org.Name == nameKey)
    .SingleOrDefaultAsync();
```

For the sync version, it's important that we don't block - so we can't use Result. The `Synchronously()` extension method in `Stormpath.SDK.Sync` is designed to bridge between async LINQ-to-Stormpath and vanilla LINQ:

```
return this.AsInterface.GetOrganizations()
    .Where(org => org.Name == nameKey)
    .Synchronously()
    .SingleOrDefault();
```

Hope this helps :smile: Let me know if you have any other questions.

**Comment by jwynia** [comment]
https://github.com/stormpath/stormpath-sdk-dotnet/pull/139

**Comment by nbarbettini** [comment]
Thanks again for the contribution @jwynia and @dalelotts - it's merged into develop. Are you building the SDK yourself locally, or relying on nightlies from MyGet?

**Comment by jwynia** [comment]
I actually put the functionality behind a facade in our codebase to get us
by until this shows up in the releases. The facade let us keep moving in
the mean time, and we've got a story in the back log to drop the facade
when this feature gets released.

On Wed, Feb 10, 2016 at 2:26 PM, Nate Barbettini notifications@github.com
wrote:

> Thanks again for the contribution @jwynia https://github.com/jwynia and
> @dalelotts https://github.com/dalelotts - it's merged into develop. Are
> you building the SDK yourself locally, or relying on nightlies from MyGet?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stormpath/stormpath-sdk-dotnet/issues/137#issuecomment-182569322
> .

## 

J Wynia
Software Consultant, Writer and Geek
Minneapolis, MN
j@wynia.org
"The glass isn't half full or half empty. It's just too big"
"Jack of all trades, master of none, though ofttimes better than master of
one."
http://wynia.org

**Comment by nbarbettini** [comment]
Sounds good. It'll be in the next one!
