### ISSUE TITLE
Is the IApplication object thread-safe?

### ISSUE THREAD

**Issue by maartendekker** [stormpath/stormpath-sdk-dotnet#141]
Can it be stored as a global property just like `IClient`? It doesn't seem to contain anything that might be critical on a per request basis.

If so, it seems like overkill to request it every time from the Stormpath API. Also, if this is the case, maybe it would be a good idea to change it in `Readme.md`, since `IApplication` is discussed immediately after the remark that `IClient` is thread-safe, and thus implicitly saying that `IApplication` is not.

**Comment by nbarbettini** [comment]
Good question. The simple answer is: yes, `IApplication` should be perfectly thread-safe. I agree that the documentation could be a little clearer on this point.

The more complex answer: if you have caching turned on, requesting it each time will simply result in an instant cache read (until the cache TTL). If you ever need to disable or modify the Application in Stormpath, this is a better option since you know that after the object expires from the cache, it will be updated to the current server state.

That's why I recommend holding onto the `IClient` and then retrieving everything else as needed per-request. With caching, the difference should be negligible.

**Comment by maartendekker** [comment]
Alright, that's clear.

Concerning the caching. I have noticed - while monitoring HTTP traffic using Fiddler - that out of the box some requests already seem to be cached internally - while others don't seem to be. For example, getting an _account_, only results in an HTTP request the first time, subsequent times it doesn't show up in Fiddler. However, getting an _application_ results in an HTTP request every time (hence, the original question about `IApplication`).
1. Can you elaborate a little on how the default caching mechanism works? The above situation leaves me a little puzzled.
2. Where can the caching be configured? I tried looking for options in `ClientBuilder`, but didn't see any. I did see the `Stormpath.SDK.Redis` code, but am not sure if this is part of any default caching mechanism, or a possible hook to connect to an external Redis server.

I understand these are probably things that will be clearly documented in the future when you reach 1.0, but for now any info is greatly appreciated!

**Comment by nbarbettini** [comment]
That's odd. **Tl;dr** - `IApplication` should be cached. If it's not, can you send a repro project? Could be a bug.

To elaborate:

**1 -** The caching mechanism (if enabled) will always cache reads and writes of **single** resources, so that if you do a `GetResourceAsync<TType>(href)` again for the same `href`, it will not hit the API.

Collection resources are different. Collection access is not cached, but the items inside are. Querying or searching a Stormpath collection will **always** result in a network request, but when the collection items come back, they are silently shoveled into the cache. If in the future, a request is made for a single resource matching that `href`, it'll be a cache read.

This is all subject to the cache TTL and TTI. You can specify a per-resource-type TTL/TTI; otherwise the default TTL/TTI are used. (If nothing is specified at all, the default TTL and TTI are both 60 minutes.)

**2 -** Configuration is done on the `IClientBuilder`, like so:

```
clientBuilder.SetCacheProvider(
    CacheProviders.InMemoryCache()
        .WithDefaultTimeToLive(TimeSpan.FromMinutes(10))
        .WithDefaultTimeToIdle(TimeSpan.FromMinutes(5))
        .Build());
```

There are more examples in the API documentation for [ICacheProviderBuilder](http://docs.stormpath.com/dotnet/api/html/T_Stormpath_SDK_Cache_ICacheProviderBuilder.htm).

**3 -** The `Stormpath.SDK.Redis` package is indeed for hooking into an external Redis server. The default (in-memory) cache works fine on a single machine, but using it in a cluster would be problematic. Hence the need for a distributed caching solution. The Redis code is intended as a canonical example of how to hook into the plugin system in the SDK and write an adapter for whatever distributed cache you might be using.

This will absolutely be better-documented in the future! Sorry that it's not all there in the docs yet. It'll be rectified soon. Hope this helps!

Feel free to continue with any follow-up questions. I'm happy to explain any bits that don't make sense. :+1:

**Comment by maartendekker** [comment]
After reading the above, it all makes sense.

I created a support method in my project that gets the right `IApplication` instance every time I would need it. In that method I used the same code as in the `Readme.md`:

``` csharp
var myApp = await client.GetApplications()
    .Where(x => x.Name == "My Application")
    .SingleAsync();
```

As you describe in your explanation above, the caching mechanism only works for single resources. Since `GetApplications` is querying a Stormpath collection, it would result in a network request every time. The `IApplication` instance I get back, **is** in fact cached, but since I never queried for it directly, it was never hit.

What I do now is only run the above code only once during application initialization (right after I instantiate my global `IClient`.) I then store `myApp.Href` in a global property (e.g. `myAppHref`.) Finally, my support method then uses that global property in the following way:

``` csharp
var myApp = await client.GetApplicationAsync(myAppHref);
```

All caching then works as expected. 

Doing things this way, my original question (about if storing an `IApplication` instance globally is thread safe, to prevent unnecessary request) is no longer a concern to me. A little paragraph about how the caching mechanism works in the `Readme.md`, would be very beneficial for new users I think (they might not even know it is there, even though it is a very cool feature!) And then maybe also a little :bulb: section in the `IApplication` paragraph to note that querying for an application that way does **not** hit the cache.

One final question. What is the proper way to temporarily disable the caching mechanism during development time? I like to get a feel for all the requests that are happening while building new functionality.

**Comment by nbarbettini** [comment]
Yep, that's exactly how I'd recommend doing it: cache the Application `href` and then use that to retrieve the application directly. Unless you expect your Application `href` to change, you could probably skip the querying at the beginning, too, and simply store the `href` as a static configuration value or in an environment variable.

Disabling the caching is done when building the `IClient`, by simply doing:

```
clientBuilder.SetCacheProvider(CacheProviders.Create().DisabledCache())
```

... caching will then be disabled for the life of the `IClient`.

Thanks for the documentation suggestions - much appreciated! Readme.md is kind of a stop-gap for now; full documentation (that better explains these points) is coming soon.
