### ISSUE TITLE
Reduce the number of required interfaces to abstract Stormpath as a provider

### ISSUE THREAD

**Issue by DarinMacRae** [stormpath/stormpath-sdk-dotnet#195]
Let's say I want to abstract away which provider I use...  
(This is entirely hypothetical since who would ever use another provider!?)  

Let's say I create this naive and simple abstraction:  

```
public class StormpathDirectoryProvider : IDirectoryProvider<Account>
{
    private const string StormPathHref = "https://api.stormpath.com/v1";

    private readonly IClient client;
    private readonly IDirectory directory;
    private readonly IApplication application;

    public StormpathDirectoryProvider(IClient client, IDirectory directory, IApplication application)
    {
        this.client = client;
        this.directory = directory;
        this.application = application;
    }
...
```

In order to create accounts, get accounts, and authenticate accounts it seems like I have to provide at least 3 interfaces, namely, IClient, IDirectory, and IApplication. (There could be more since I'm just getting started.)

Wouldn't it be better if I only needed to provide IDirectory and I could do any of those operations on it? In the end, its the directory that stores the accounts, supports authorizations, has the policies, and the workflows.

Would you consider making IDirectory (or something like it) have all of the necessary methods on it to simplify this kind of abstraction?

**Comment by nbarbettini** [comment]
We want to avoid adding "everything and the kitchen sink" to an interface like IApplication or IDirectory because it starts to become too unwieldy. That being said, there is definitely room for improvement here - thank you for the suggestion!

I think that a better abstraction here might be to simply depend on IClient and the href (string) of the directory address. Given those, you could retrieve anything else you needed.

... With the caveat that if your abstraction needs to expose authentication, it would require an IApplication or an application href as well. Authentications require an Application, because auth attempts start with applications in Stormpath.

**Comment by nbarbettini** [comment]
Closing this since we won't be making any interface changes until 1.0 (a breaking change). Later this year I will be posting a design draft for the direction of 1.0 and beyond, so I'll be sure to ping you to get your thoughts. 😄
