### ISSUE TITLE
"Cache Provider Disposed" exception when calling GetAccountAsync

### ISSUE THREAD

**Issue by lostrouter** [stormpath/stormpath-sdk-dotnet#250]
call fails here.  if i refactor my code to return the `IAccount` from `AuthenticateUser` i don't get this exception.
```
var authResult = await _authenticationContext.RunStormpathFunc(async client => await _authenticationContext.AuthenticateUser(client, query.Username, query.Password)).ConfigureAwait(false);
var account = await authResult.getAccountAsync();
```
supporting functions
```
public async Task RunStormpathFunc(Func<IClient, Task> stormpathFunc)
{
  using (var stormpathClient = BuildClient())
  {
    await stormpathFunc(stormpathClient).ConfigureAwait(false);
  }
}
```

```
public async Task<IAuthenticationResult> AuthenticateUser(IClient client, string username, string password)
{
  var myApp = await client.GetResourceAsync<IApplication>(_href).ConfigureAwait(false);
  var loginResult = await myApp.AuthenticateAccountAsync(username, password).ConfigureAwait(false);
  return loginResult}
```

```
private IClient BuildClient()
{
  return Clients.Builder()
    .SetApiKeyId(_id)
    .SetApiKeySecret(_secret)
    .SetConnectionTimeout(new TimeSpan(0, 0, 0, 5)) // 5 second timeout
    .Build();
}
```

**Comment by nbarbettini** [comment]
Hey @lostrouter, thanks for sharing your code. That helps me understand what's going on here.

The error is occurring because you're disposing the `IClient` inside `RunStormpathFunc`, and then trying to get an object from the client.

It's not as clear as it should be in the docs, but the `IClient` should always be treated as a singleton. In other words, you should only run `Clients.Builder()...Build()` once, when your app starts up, and keep that `IClient` instance around. That will avoid issues like this.

Let me know if you need further clarification!

**Comment by lostrouter** [comment]
@nbarbettini thank you for the info on how properly use `IClient`.  that clears it up.
