### ISSUE TITLE
href on AuthenticationResult is null

### ISSUE THREAD

**Issue by jmoring** [stormpath/stormpath-sdk-dotnet#63]
After a successful call to Application.AuthenticateAccountAsync the HREF in IAuthenticationResult is null.

**Comment by nbarbettini** [comment]
Thanks for reporting this! This was an oversight - `IAuthenticationResult` shouldn't actually implement `IResource` (and shouldn't have an href property). Will be fixed in [0.3](https://github.com/stormpath/stormpath-sdk-dotnet/milestones/0.3.0) or earlier.

In the meantime, ignore `Href` on this object. `GetAccountAsync` is the only operation it should support.
