### ISSUE TITLE
Add convenience methods for getting single resources

### ISSUE THREAD

**Issue by bbadjari** [stormpath/stormpath-sdk-dotnet#86]
Add support for the `Href` field from `IResource` for use in LINQ queries.

Example:

    async Task<IGroup> GetGroup(string href)
    {
        IClient client = ...;
        return await client.GetGroups().Where(group => group.Href == href);
    }

**Comment by nbarbettini** [comment]
What about:
``` csharp
return await client.GetResourceAsync<IGroup>(href);
```

Would being able to match an `href` from within LINQ provide any additional benefit?

**Comment by bbadjari** [comment]
I guess not, other than using LINQ consistently as with other fields, such as:

    async Task<IGroup> GetGroup(string name)
    {
        IClient client = ...;
        return await client.GetGroups().Where(group => group.Name == name);
    }

Perhaps it's just my preference. :-)

**Comment by nbarbettini** [comment]
It's my preference, too :smile: I looked into making this syntax work before, but the [underlying API](http://docs.stormpath.com/rest/product-guide/#search) doesn't currently allow the `href` field to be used in a search term.

It could be implemented using client-side trickery, but it would be considerably slower than using `GetResourceAsync`, since the entire collection would have to be enumerated locally to find it. It's much faster and more efficient to simply grab the resource directly, even though the syntax is different.

:bulb: Perhaps it would be nice to have additional convenience methods on `IClient`? `GetGroup(href)` could just be shorthand for `GetResourceAsync<IGroup>`.

**Comment by bbadjari** [comment]
It would be nice, but not really necessary. If you'd like to add this it would certainly be low priority.

**Comment by nbarbettini** [comment]
If I have a chance to get it into release 0.4, I'll add these methods:

``` csharp
IAccount GetAccountAsync(href);
IApplication GetApplicationAsync(href);
IDirectory GetDirectoryAsync(href);
IGroup GetGroupAsync(href);
```

... and their synchronous counterparts.
